#ifndef LU_LSS_SCHM_DSC_h
#define LU_LSS_SCHM_DSC_h

#include "LuGenOp.h"
enum LSS_INPUT_NAMES{
LSS_IN_NAME__LSSIN1 = 1 ,
LSS_IN_NAME__MUTE_I     ,
LSS_IN_NAME__BLOCK_I    ,
 LSS_IN_NAME__RESET_I   ,
TOTAL_LSS_IN = LSS_IN_NAME__RESET_I
};

enum LSS_OUTPUT_NAMES{
LSS_OUT_NAME_ALARM = 1,
LSS_OUT_NAME_MUTE,
TOTAL_LSS_OUTPUT = LSS_OUT_NAME_MUTE
};


enum LSS_MNU_SELECTION1{
LSS_MODE_SIMPLE = 0,
LSS_MODE_TRIGGER,
LSS_MODE_PERIOD,
TOTAL_LSS_MODES
};
//

enum LSS_SCHEMATIC_LU_ORDER_NUMS{
LSS_NOT_01__1_1,
LSS_NOT_02__1_1,
LSS_NOT_03__1_1,
LSS_NOT_04__1_1,
LSS_DELAY_05_1_1,
LSS_DELAY_06_1_1,
LSS_OR_07__2_1,
LSS_NOT_08__1_1,
LSS_NOT_09__1_1,
LSS_OR_10__2_1,
LSS_D_TRG_11__4_2, 
LSS_AND_12__3_1,
LSS_DELAY_13__1_1,
LSS_OR_14__3_1,
LSS_AND_15__3_1,
LSS_AND_16__3_1,
LSS_AND_17__3_1,
LSS_AND_18__2_1,
LSS_AND_19__2_1,
LSS_AND_20__3_1,
LSS_OR_21__3_1,
LSS_OR_22__3_1,
LSS_AND_23__4_1,
LSS_AND_24__4_1,
LSS_AND_25__4_1,
LSS_AND_26__4_1,
LSS_OR_27__2_1,
LSS_OR_28__2_1,
LSS_D_TRG_29__4_2,
IN_SIMPLE_SELECTOR ,
IN_TRIGGER_SELECTOR,
IN_PERIOD_SELECTOR,
IN_LSS_LSSIN1  ,
IN_LSS_MUTE_I  ,
IN_LSS_RESET_I ,
IN_LSS_BLOCK_I ,
OUT_LSS_ALARM  ,
OUT_LSS_MUTE,
IN_LSS_VCC,
IN_LSS_GROUND,
//====================
//Psevdonims
//====================
LSS_NAME_LSSIN = IN_LSS_LSSIN1,
LSS_NAME_LSSIN_IMP = LSS_DELAY_05_1_1,
LSS_NAME_LSS_D     = LSS_D_TRG_11__4_2,
LSS_NAME_TIME_TR   = LSS_OR_07__2_1,
LSS_NAME_NORMAL    = IN_SIMPLE_SELECTOR,
LSS_NAME_BLOCK_INV = LSS_NOT_08__1_1,
LSS_NAME_MUTE_INV  = LSS_D_TRG_29__4_2,
LSS_NAME_MUTE_DIR  = LSS_D_TRG_29__4_2,
//--------------------
TOTAL_PROCESS_LSS_LU
};

enum LSS_SCH_ORDER_NUM_OFFSET_OUTS{

OFFSET_OUT_LSS_NOT_01__1_1 = 0,
OFFSET_OUT_LSS_NOT_02__1_1,
OFFSET_OUT_LSS_NOT_03__1_1,
OFFSET_OUT_LSS_NOT_04__1_1,
OFFSET_OUT_LSS_DELAY_05_1_1,
OFFSET_OUT_LSS_DELAY_06_1_1,
OFFSET_OUT_LSS_OR_07__2_1,
OFFSET_OUT_LSS_NOT_08__1_1,
OFFSET_OUT_LSS_NOT_09__1_1,
OFFSET_OUT_LSS_OR_10__2_1,
OFFSET_OUT_LSS_D_TRG_11__4_2 , 
OFFSET_OUT_LSS_AND_12__3_1 = OFFSET_OUT_LSS_D_TRG_11__4_2 + 2,
OFFSET_OUT_LSS_DELAY_13__1_1,
OFFSET_OUT_LSS_OR_14__3_1,
OFFSET_OUT_LSS_AND_15__3_1,
OFFSET_OUT_LSS_AND_16__3_1,
OFFSET_OUT_LSS_AND_17__3_1,
OFFSET_OUT_LSS_AND_18__2_1,
OFFSET_OUT_LSS_AND_19__2_1,
OFFSET_OUT_LSS_AND_20__3_1,
OFFSET_OUT_LSS_OR_21__3_1,
OFFSET_OUT_LSS_OR_22__3_1,
OFFSET_OUT_LSS_AND_23__4_1,
OFFSET_OUT_LSS_AND_24__4_1,
OFFSET_OUT_LSS_AND_25__4_1,
OFFSET_OUT_LSS_AND_26__4_1,
OFFSET_OUT_LSS_OR_27__2_1,
OFFSET_OUT_LSS_OR_28__2_1,
OFFSET_OUT_LSS_D_TRG_29__4_2, 
OFFSET_OUT_IN_LSS_NORMAL = OFFSET_OUT_LSS_D_TRG_29__4_2 + 2,
OFFSET_OUT_IN_LSS_TRIGGER  ,
OFFSET_OUT_IN_LSS_TIMELIMITED  ,
OFFSET_OUT_IN_LSS_LSSIN1  ,
OFFSET_OUT_IN_LSS_MUTE_I  ,
OFFSET_OUT_IN_LSS_RESET_I ,
OFFSET_OUT_IN_LSS_BLOCK_I ,
OFFSET_OUT_OUT_LSS_ALARM  ,
OFFSET_OUT_OUT_LSS_MUTE,
OFFSET_OUT_IN_LSS_VCC,
OFFSET_OUT_IN_LSS_GROUND,
OFFSET_OUT_LSS_NAME_LSSIN     = OFFSET_OUT_IN_LSS_LSSIN1,
OFFSET_OUT_LSS_NAME_LSSIN_IMP = OFFSET_OUT_LSS_DELAY_05_1_1,
OFFSET_OUT_LSS_NAME_LSS_D     = OFFSET_OUT_LSS_D_TRG_11__4_2,
OFFSET_OUT_LSS_NAME_TIME_TR   = OFFSET_OUT_LSS_OR_07__2_1,
OFFSET_OUT_LSS_NAME_NORMAL    = OFFSET_OUT_IN_LSS_NORMAL,
OFFSET_OUT_LSS_NAME_BLOCK_INV = OFFSET_OUT_LSS_NOT_08__1_1,
OFFSET_OUT_LSS_NAME_MUTE_INV  = OFFSET_OUT_LSS_D_TRG_29__4_2 + 1,
OFFSET_OUT_LSS_NAME_MUTE_DIR  = OFFSET_OUT_LSS_D_TRG_29__4_2,
TOTAL_LSS_LU_CALC_POINT = OFFSET_OUT_IN_LSS_GROUND + 1
 
};

#endif


