#ifndef LU_MFT_DSC_h
#define LU_MFT_DSC_h

#include "LuGenOp.h"
enum MFT_INPUT_NAMES{
MFT_IN_NAME__MFTIN = 1,
MFT_IN_NAME__RESET_I,

TOTAL_MFT_IN = MFT_IN_NAME__RESET_I
};
enum MFT_OUTPUT_NAMES{
MFT_OUT_NAME__MFT_IMP_DIR_OUT = 1,
MFT_OUT_NAME__MFT_DEL_OUT,
MFT_OUT_NAME__MFT_IMP_INV_OUT,
TOTAL_MFT_OUTPUT = MFT_OUT_NAME__MFT_IMP_INV_OUT

};



#endif
