#ifndef __COMPONENTENUM_H
#define __COMPONENTENUM_H

enum {
 DVBIGCOMPONENT          ,//0
 DVSMALLCOMPONENT        ,//1
 DOUTSMALLCOMPONENT      ,//2
 DOUTBIGCOMPONENT        ,//3
 SDISMALLCOMPONENT       ,//4
 SDIBIGCOMPONENT         ,//5
 CONFIGBIGCOMPONENT      ,//6
 GIBIGCOMPONENT          ,//7
 CGSBIGCOMPONENT         ,//8
 SZSBIGCOMPONENT         ,//9
 MFTBIGCOMPONENT         ,//10
 DTRBIGCOMPONENT         ,//11
 TSSMALLCOMPONENT        ,//12
 TSBIGCOMPONENT          ,//13
 TUSMALLCOMPONENT        ,//14
 TUBIGCOMPONENT          ,//15
 ANDBIGCOMPONENT         ,//16
 ORBIGCOMPONENT          ,//17
 XORBIGCOMPONENT         ,//18
 NOTBIGCOMPONENT         ,//19
 COMMONSMALLCOMPONENT    ,//20
 COMMONBIGCOMPONENT      ,//21
 MEBIGCOMPONENT          ,//22
 REGBIGCOMPONENT         ,//23
 RPRBIGCOMPONENT         ,//24
 RPRSMALLCOMPONENT       ,//25
 KEYSMALLCOMPONENT       ,//26
 RMTKEYSMALLCOMPONENT    ,//27
 AISMALLCOMPONENT        ,//28
 PKVBIGCOMPONENT         ,//29
 IUSMALLCOMPONENT        ,//30
 YUSTBIGCOMPONENT        ,//31
 RPOBIGCOMPONENT         ,//32
 TOTAL_COMPONENT         ,//33

 MARKER_OUTPERIMETR   = 100000,
 MARKER_ERRORPERIMETR = 100001,
 MARKER_ERRORDIAPAZON = 100002,
};

//макс к-во входов у субобекта
#define MAXIMUMI 5
//макс размер буфера записи
#define MAXIMUMTW 128

#endif
