#ifndef __COMPONENTENUM_H
#define __COMPONENTENUM_H

enum {
 DVBIGCOMPONENT          ,//0
 DVSMALLCOMPONENT        ,//1
 DOUTSMALLCOMPONENT      ,//2
 DOUTBIGCOMPONENT        ,//3
 SDISMALLCOMPONENT       ,//4
 SDIBIGCOMPONENT         ,//5
 RMTKEYSMALLCOMPONENT    ,//6
 SDI3COLORSMALLCOMPONENT ,//7
 CONFIGBIGCOMPONENT      ,//8
// RESDBIGCOMPONENT        ,//9
// BASDBIGCOMPONENT        ,//10
 GIBIGCOMPONENT          ,//11
 CGSBIGCOMPONENT         ,//12
 SZSBIGCOMPONENT         ,//13
 MFTBIGCOMPONENT         ,//14
 DTRBIGCOMPONENT         ,//15
 TSSMALLCOMPONENT        ,//16
 TSBIGCOMPONENT          ,//17
 TUSMALLCOMPONENT        ,//18
 TUBIGCOMPONENT          ,//19
 ANDBIGCOMPONENT         ,//20
 ORBIGCOMPONENT          ,//21
 XORBIGCOMPONENT         ,//22
 NOTBIGCOMPONENT         ,//23
 COMMONSMALLCOMPONENT    ,//24
 COMMONBIGCOMPONENT      ,//25
 MEBIGCOMPONENT          ,//26
 REGBIGCOMPONENT         ,//27
 RPRBIGCOMPONENT         ,//28
 RPRSMALLCOMPONENT       ,//29
 KEYSMALLCOMPONENT       ,//30
 AISMALLCOMPONENT        ,//31
 PKVBIGCOMPONENT         ,//32
 IUSMALLCOMPONENT        ,//33
 YUSTBIGCOMPONENT        ,//34
 RPOBIGCOMPONENT         ,//35
 TOTAL_COMPONENT         ,//36

 MARKER_OUTPERIMETR   = 100000,
 MARKER_ERRORPERIMETR = 100001,
 MARKER_ERRORDIAPAZON = 100002,
};

//макс к-во входов у субобекта
#define MAXIMUMI 5
//макс размер буфера записи
#define MAXIMUMTW 128

#endif
