#ifndef __CONST_MENU_LEVEL_PASSWORD__
#define __CONST_MENU_LEVEL_PASSWORD__

#define EKRAN_LEVEL_PASSWORD          0
#define EKRAN_LEVEL_CHOOSE_PASSWORDS  (EKRAN_RANGUVANNJA_D_NOT16 + 1)
#define EKRAN_LEVEL_SET_NEW_PASSWORD  (EKRAN_LEVEL_CHOOSE_PASSWORDS + 1)

#define MAX_ROW_FOR_CHOOSE_PASSWORDS  1

#define  INDEX_OF_PASSWORD1                     0
#define  INDEX_OF_PASSWORD2                     1

#endif
