#ifndef __CONST_CHOOSE_SETTING_LOGICAL_NODES_MENU2__
#define __CONST_CHOOSE_SETTING_LOGICAL_NODES_MENU2__

enum __index_settings_D_m2
{
  INDEX_LIST_SETTINGS_D_M2_DELAY = 0,
  
  MAX_ROW_LIST_SETTINGS_D_M2
};

enum __index_settings_DC_m2
{
  INDEX_LIST_SETTINGS_DC_M2_DELAY = 0,
  INDEX_LIST_SETTINGS_DC_M2_CONTROL,
  
  MAX_ROW_LIST_SETTINGS_DC_M2
};


#endif
