#ifndef __CONST_PARAM_LOGICAL_NODES_MENU2__
#define __CONST_PARAM_LOGICAL_NODES_MENU2__

#define MAX_ROW_FOR_PARAM_LIST_LOGICAL_NODES  NUMBER_ALL_BLOCKS

enum _index_param_list_logical_nodes_m2
{
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_CONTROL_BLOCK = 0,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_INPUTS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_OUTPUTS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_LEDS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_BUTTON,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_ALARM,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_GROUP_ALARMS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_ANDS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_ORS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_XORS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_NOTS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_TIMERS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_TRIGGERS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_MEANDERS,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_TU,
  
  MAX_ROW_PARAM_LIST_LOGICAL_NODES_M2
};



#endif
