#ifndef __CONST_MENU_VER2__
#define __CONST_MENU_VER2__

enum _menu2_levels
{
  MAIN_MANU2_LEVEL = 0,
    TIME_MANU2_LEVEL,
    MEASUREMENT_MENU2_LEVEL,
    INPUTS_OUTPUTS_MENU2_LEVEL,
      INPUTS_MENU2_LEVEL,
      OUTPUTS_MENU2_LEVEL,
    REGISTRATORS_MENU2_LEVEL,
    LIST_SETTINGS_MENU2_LEVEL,
      CONFIGURATION_MENU2_LEVEL,
      LIST_TIMERS_MENU2_LEVEL,
        LIST_SETTINGS_TIMER_MENU2_LEVEL,
          DELAY_TIMER_MENU2_LEVEL,
          CTRL_TIMER_MENU2_LEVEL,
      LIST_MEANDERS_MENU2_LEVEL,
        LIST_SETTINGS_MEANDER_MENU2_LEVEL,
          DELAY_MEANDER_MENU2_LEVEL,
      LIST_SETTINGS_BIOS_MENU2_LEVEL,
        LIST_INPUTS_MENU2_LEVEL,
          LIST_SETTINGS_INPUT_MENU2_LEVEL,
            DELAY_INPUT_MENU2_LEVEL,
            CTRL_INPUT_MENU2_LEVEL,
        LIST_OUTPUTS_MENU2_LEVEL,
          LIST_SETTINGS_OUTPUT_MENU2_LEVEL,
            CTRL_OUTPUT_MENU2_LEVEL,
        LIST_LEDS_MENU2_LEVEL,
          LIST_SETTINGS_LED_MENU2_LEVEL,
            CTRL_LED_MENU2_LEVEL,
      LANGUAGE_MENU2_LEVEL,
      LIST_SETTINGS_COMMUNIACATION_PARAMETERS_MENU2_LEVEL,
        NAME_OF_CELL_MENU2_LEVEL,
    DIAGNOSTICS_MENU2_LEVEL,
    LABELS_MENU2_LEVEL,
      CONFIG_LABEL_MENU2_LEVEL,
      SETTINGS_LABEL_MENU2_LEVEL,
    INFO_MENU2_LEVEL,
      DATE_TIME_INFO_MENU2_LEVEL,
    
  PASSWORD_MENU2_LEVEL,
  
  MAX_NUMBER_MENU2_LEVEL
};

#endif
