#ifndef __CONST_LIST_SETTINGS_PARAM_MENU2__
#define __CONST_LIST_SETTINGS_PARAM_MENU2__

enum __index_list_settings_param_m2
{
  INDEX_LIST_SETTINGS_PARAM_M2_INPUT = 0,
  INDEX_LIST_SETTINGS_PARAM_M2_OUTPUT,
  INDEX_LIST_SETTINGS_PARAM_M2_LED,
  INDEX_LIST_SETTINGS_PARAM_M2_ALARM,
  INDEX_LIST_SETTINGS_PARAM_M2_GROUP_ALARM,
  INDEX_LIST_SETTINGS_PARAM_M2_TIMER,
  INDEX_LIST_SETTINGS_PARAM_M2_MEANDER,
  
  MAX_ROW_LIST_SETTINGS_PARAM_M2
};


#endif
