#ifndef __CONST_EDITOR_LOGICAL_NODES_MENU2__
#define __CONST_EDITOR_LOGICAL_NODES_MENU2__

#define MAX_ROW_FOR_EDITOR_LIST_LOGICAL_NODES                   NUMBER_ALL_BLOCKS

enum _index_editor_list_logical_nodes_m2
{
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_CONTROL_BLOCK = 0,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_INPUTS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_OUTPUTS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_LEDS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_BUTTON,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_ALARM,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_GROUP_ALARMS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_ANDS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_ORS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_XORS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_NOTS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_TIMERS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_TRIGGERS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_MEANDERS,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_TU,
  INDEX_EDITOR_LIST_LOGICAL_NODES_M2_LOG,
  
  MAX_ROW_EDITOR_LIST_LOGICAL_NODES_M2
};



#endif
