#ifndef __CONST_MENU_VER2__
#define __CONST_MENU_VER2__

enum _menu2_levels
{
  MAIN_MANU2_LEVEL = 0,
    TIME_MANU2_LEVEL,
    MEASUREMENT_MENU2_LEVEL,
    INPUTS_OUTPUTS_MENU2_LEVEL,
      INPUTS_MENU2_LEVEL,
      OUTPUTS_MENU2_LEVEL,
    REGISTRATORS_MENU2_LEVEL,
    LIST_SETTINGS_MENU2_LEVEL,
      CONFIGURATION_MENU2_LEVEL,
    DIAGNOSTICS_MENU2_LEVEL,
    LABELS_MENU2_LEVEL,
      CONFIG_LABEL_MENU2_LEVEL,
      SETTINGS_LABEL_MENU2_LEVEL,
    INFO_MENU2_LEVEL,
      DATE_TIME_INFO_MENU2_LEVEL,
    
  PASSWORD_MENU2_LEVEL,
  
  MAX_NUMBER_MENU2_LEVEL
};

#endif
