#ifndef __CONST_MENU_STATE_INPUTS_OUTPUTS__
#define __CONST_MENU_STATE_INPUTS_OUTPUTS__

#define EKRAN_LIST_INPUTS_OUTPUTS       (EKRAN_CHOOSE_SETTINGS_CTRL_PHASE + 1)
#define EKRAN_STATE_INPUTS              (EKRAN_LIST_INPUTS_OUTPUTS + 1)
#define EKRAN_STATE_OUTPUTS             (EKRAN_STATE_INPUTS + 1)


#endif
