#ifndef __CONST_MENU_VER2__
#define __CONST_MENU_VER2__

enum _menu2_levels
{
  MAIN_MANU2_LEVEL = 0,
    TIME_MANU2_LEVEL,
    MEASUREMENT_MENU2_LEVEL,
    INPUTS_OUTPUTS_MENU2_LEVEL,
      INPUTS_MENU2_LEVEL,
      OUTPUTS_MENU2_LEVEL,
    REGISTRATORS_MENU2_LEVEL,

    DIAGNOSTICS_MENU2_LEVEL,
    
  PASSWORD_MENU2_LEVEL,
  
  MAX_NUMBER_MENU2_LEVEL
};

#endif
