#ifndef __CONST_MENU_CHOSE_SETTING_UVV__
#define __CONST_MENU_CHOSE_SETTING_UVV__

#define EKRAN_CHOOSE_SETTINGS_UVV        (EKRAN_RANGUVANNJA_ALARMS2 + 1)
#define EKRAN_DOPUSK_DV_UVV              (EKRAN_CHOOSE_SETTINGS_UVV + 1)
#define EKRAN_TYPE_INPUT_SIGNAL_UVV      (EKRAN_DOPUSK_DV_UVV + 1)


#endif
