#ifndef __CONST_MENU_POINT_TIME_SETTINGS__
#define __CONST_MENU_POINT_TIME_SETTINGS__

#define EKRAN_POINT_TIME_SETTINGS            (EKRAN_DATE_TIME_PZ + 1)
#define EKRAN_POINT_TIME_SETPOINT            (EKRAN_POINT_TIME_SETTINGS + 1)
#define EKRAN_POINT_TIME_RANGUVANNJA         (EKRAN_POINT_TIME_SETPOINT + 1)


#endif
