#ifndef __CONST_MENU_CHOSE_COMMUNICATION_PARAMETERS__
#define __CONST_MENU_CHOSE_COMMUNICATION_PARAMETERS__

#define EKRAN_CHOSE_COMMUNICATION_PARAMETERS      (EKRAN_TYPE_INPUT_SIGNAL_UVV + 1)
#define EKRAN_VIEW_NAME_OF_CELL                   (EKRAN_CHOSE_COMMUNICATION_PARAMETERS + 1)
#define EKRAN_ADDRESS                             (EKRAN_VIEW_NAME_OF_CELL + 1)
#define EKRAN_CHOSE_SETTING_RS485                 (EKRAN_ADDRESS + 1)
#define EKRAN_VIEW_SPEED_RS485                    (EKRAN_CHOSE_SETTING_RS485 + 1)
#define EKRAN_VIEW_PARE_RS485                     (EKRAN_VIEW_SPEED_RS485 + 1)
#define EKRAN_VIEW_STOP_BITS_RS485                (EKRAN_VIEW_PARE_RS485 + 1)
#define EKRAN_VIEW_TIMEOUT_RS485                  (EKRAN_VIEW_STOP_BITS_RS485 + 1)

#endif
